name: Pragmatic

on:
  push:
    tags:
      - "*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  windowsBuild:
    name: Windows Build
    runs-on: windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: recursive
          token: ${{secrets.CI}}

      - name: Print dirs
        shell: cmd
        run: |
          dir

      - name: PIP
        shell: cmd
        run: |
          pip install twine
          pip install progressbar

      - name: Build & Upload
        shell: cmd
        run: |
          call python .\Scripts\Utility\publish.py SquareRoundCurly ${{secrets.PYPI}}

      - uses: EndBug/add-and-commit@v9
        with:
          message: '[AUTO] Increment version]'

      - name: Zip
        shell: cmd
        run: |
          dir
          dir dist
          call 7z a Pragmatic.zip .\dist\*

      - name: Publish manual release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.version}} != ""
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: Pragmatic.zip
            name: ${{ github.event.inputs.version}}
            tag_name: ${{ github.event.inputs.version}}

      - name: Publish tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: Pragmatic.zip

      - name: Get LLVM
        shell: cmd
        run: |
          call python ./pragmatic_runner.py download

      - name: Configure
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/configure.py

      - name: Build
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/build.py

      - name: Zip
        shell: cmd
        run: |
          dir
          dir PragmaticPlugin
          dir PragmaticPlugin\Build
          dir PragmaticPlugin\Build\RelWithDebInfo
          call 7z a PragmaticPlugin.zip .\PragmaticPlugin\Build\RelWithDebInfo\*

      - name: Publish manual release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.version}} != ""
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: PragmaticPlugin.zip
            name: ${{ github.event.inputs.version}}
            tag_name: ${{ github.event.inputs.version}}

      - name: Publish tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: PragmaticPlugin.zip