name: PragmaticPlugin

on:
  push:
    tags:
      - "*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  windowsBuild:
    name: Windows Build
    runs-on: windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{secrets.CI}}

      - name: Print dirs
        shell: cmd
        run: |
          dir

      - name: Configure
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/Configure.py

      - name: Build
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/Build.py

      - name: Zip
        shell: cmd
        run: 7z a PragmaticPlugin.zip ./PragmaticPlugin/Build/RelWithDebInfo/*

      - name: Publish manual release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.version}} != ""
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: PragmaticPlugin.zip
            name: ${{ github.event.inputs.version}}
            tag_name: ${{ github.event.inputs.version}}

      # - name: Delete manual tag
      #   uses: actions/github-script@v3
      #   if: ${{ github.event.inputs.version}} != ""
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}          
      #     script: |
      #       try {
      #           await github.git.deleteRef({
      #             owner: context.repo.owner,
      #             repo: context.repo.repo,
      #             ref: "tags/${{ github.event.inputs.version}}"
      #           })
      #       } catch (e) {
      #         console.log("The nightly tag doesn't exist yet: " + e)
      #       }

      - name: Publish tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: PragmaticPlugin.zip
