name: PragmaticPlugin

on:
  push:
    tags:
      - "*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  windowsBuild:
    name: Windows Build
    runs-on: windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{secrets.CI}}

      - name: Print dirs
        shell: cmd
        run: |
          dir

      - name: Get progressbar
        shell: cmd
        run: |
          pip install progressbar

      - name: Get LLVM
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/get_LLVM.py

      - name: Configure
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/configure.py

      - name: Build
        shell: cmd
        run: |
          call python ./PragmaticPlugin/Scripts/build.py

      - name: Zip
        shell: cmd
        run: |
          dir
          dir PragmaticPlugin
          dir PragmaticPlugin\Build
          dir PragmaticPlugin\Build\RelWithDebInfo
          call 7z a PragmaticPlugin.zip .\PragmaticPlugin\Build\RelWithDebInfo\*


      - name: Publish manual release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.version}} != ""
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: PragmaticPlugin.zip
            name: ${{ github.event.inputs.version}}
            tag_name: ${{ github.event.inputs.version}}

      - name: Publish tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
            GITHUB_TOKEN: ${{secrets.CI}}
        with:
            files: PragmaticPlugin.zip
